name = "designer-bookmarks-api"
main = "src/index.ts"
compatibility_date = "2025-05-18"

workers_dev = true

# 绑定自定义域名 api.designnest.ccwu.cc
[[routes]]
pattern = "api.designnest.ccwu.cc/*"
zone_name = "designnest.ccwu.cc"
